services:
  - docker
language: generic
env:
  matrix:
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="melodic"
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .ci_config -b legacy
script:
  - .ci_config/travis.sh

